import type { EshopOrder } from '../types'
import type { OrderDetailData } from '@/components/erp'

export function getCustomerName(o: EshopOrder):  string { return o.customerName  || o.EshopUser?.name  || 'Zákazník' }
export function getCustomerEmail(o: EshopOrder): string { return o.customerEmail || o.EshopUser?.email || '' }
export function getCustomerPhone(o: EshopOrder): string { return o.customerPhone || o.EshopUser?.phone || '' }

export function mapEshopOrderToOrderDetail(order: EshopOrder): OrderDetailData {
  return {
    id:            order.id,
    orderNumber:   order.orderNumber,
    orderDate:     order.orderDate,
    status:        order.status,
    totalAmount:   order.totalAmount,
    totalVatAmount: order.totalVatAmount,
    paidAt:        order.paidAt,
    shippedAt:     order.shippedAt,
    customerName:  getCustomerName(order),
    customerEmail: getCustomerEmail(order) || null,
    customerPhone: getCustomerPhone(order) || null,
    customerAddress:    order.customerAddress,
    paymentReference:   order.paymentReference,
    trackingNumber:     order.trackingNumber,
    carrier:            order.carrier,
    stornoAt:           order.stornoAt,
    stornoBy:           order.stornoBy,
    stornoReason:       order.stornoReason,
    note:               order.note,
    shippingMethod:     order.shippingMethod,
    pickupPointId:      order.pickupPointId,
    pickupPointName:    order.pickupPointName,
    pickupPointAddress: order.pickupPointAddress,
    pickupPointCarrier: order.pickupPointCarrier,
    billingName:        order.billingName,
    billingCompany:     order.billingCompany,
    billingIco:         order.billingIco,
    billingStreet:      order.billingStreet,
    billingCity:        order.billingCity,
    billingZip:         order.billingZip,
    billingCountry:     order.billingCountry,
    items: order.items.map(item => ({
      id:           item.id,
      productId:    item.productId   ?? null,
      productName:  item.productName ?? null,
      quantity:     Number(item.quantity),
      unit:         item.unit,
      price:        Number(item.price),
      vatRate:      Number(item.vatRate),
      vatAmount:    Number(item.vatAmount),
      priceWithVat: Number(item.priceWithVat),
      product:      item.product ?? null,
    })),
    issuedInvoice: order.issuedInvoice ? {
      id:             order.issuedInvoice.id,
      invoiceNumber:  order.issuedInvoice.invoiceNumber,
      paymentType:    order.issuedInvoice.paymentType,
      paymentStatus:  order.issuedInvoice.paymentStatus,
      status:         order.issuedInvoice.status,
      invoiceDate:    order.issuedInvoice.invoiceDate,
      dueDate:        order.issuedInvoice.dueDate        ?? null,
      variableSymbol: order.issuedInvoice.variableSymbol ?? null,
      constantSymbol: order.issuedInvoice.constantSymbol ?? null,
      specificSymbol: order.issuedInvoice.specificSymbol ?? null,
    } : null,
    deliveryNotes: (order.deliveryNotes ?? []).map(dn => ({
      id:             dn.id,
      deliveryNumber: dn.deliveryNumber,
      deliveryDate:   dn.deliveryDate,
      status:         dn.status,
      items: dn.items.map(item => ({
        id:              item.id,
        quantity:        Number(item.quantity),
        unit:            item.unit,
        productId:       item.productId       ?? null,
        inventoryItemId: item.inventoryItemId ?? null,
        productName:     item.productName     ?? null,
        price:           item.price     != null ? Number(item.price)        : null,
        priceWithVat:    item.priceWithVat != null ? Number(item.priceWithVat) : null,
        vatRate:         item.vatRate   != null ? Number(item.vatRate)       : null,
        vatAmount:       item.vatAmount != null ? Number(item.vatAmount)     : null,
        product:         item.product ?? null,
      })),
    })),
  }
}
