export { useProducts }        from './hooks/useProducts'
export { ProductTable }       from './components/ProductTable'
export { ProductFormModal }   from './components/ProductFormModal'
export { CategoryManager }    from './components/CategoryManager'
export { VariantRow }         from './components/VariantRow'
export { TogglePill }         from './components/TogglePill'
export type { Product, Category, EshopVariant, EshopVariantForm, DraftVariant, SortField, SortDir } from './types'
