export { useInventory }          from './hooks/useInventory'
export { useProductMovements }   from './hooks/useProductMovements'
export { InventoryTable }        from './components/InventoryTable'
export { MovementTable }         from './components/MovementTable'
export { ManualAdjustmentModal } from './components/ManualAdjustmentModal'
export type { InventorySummary, StockMovement, Product, Category, SortField, SortDirection } from './types'
